### ISSUE TITLE
add `.resinci.yml` file to root

### ISSUE THREAD

**Issue by somombo** [product-os/dreamsheets-scripts#27]
```yaml
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "12"
        - "14"
        - "16"
```
